# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# bcrypt: http://www.bcrypt-generator.com/
development:
  secret_key_base: 01689a945e9841293c79fc85637dc47e71b06ac50bf14841f32f4b35c8f71439db1c0c33c9f9042f86566bcdbfdaaacd92f8e96b23d4be29a27b0e2758594e2b
  web_password: $2a$08$3b36Z.1XiBFtJ8W5V65rb.CH5TDSe.LX/naHPPbwiZFDc2.3caToa # 1234
test:
  secret_key_base: 3bbf1080c6768ec045a61dffdb8b6318d6ffc9887bb7fcda522d0bff45b993817dfbb836dadca18ca7228db173128dca759c8b15cc7211e71aacd0f35ca14bb1
  web_password: $2a$08$3b36Z.1XiBFtJ8W5V65rb.CH5TDSe.LX/naHPPbwiZFDc2.3caToa # 1234
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  web_password: <%= ENV["WEB_PASSWORD"] %> # use bcrypt
